### ISSUE TITLE
departement_code and region_id refactoring

### ISSUE THREAD

**Issue by vtedesco** [jpetitcolas/french-geography#8]
``` yaml
city_30784:
        name: "Paris"
        region_id: 75
        department_code: 056
        prefix: ""
```
- What do really represent `department_code` on the city the entity ? Shouldn't it be a 2 digit number ?
- `region_id` is referencing the department entity, we should consider renaming it `department_id`.

**Comment by jpetitcolas** [comment]
True it isn't clear after several months off this project. I'm looking at it more precisely.

**Comment by jpetitcolas** [comment]
There was a huge mistake in the INSEE file parsing. I created PR #9 to fix it. You should now get:

``` yaml
city_30784:
        name: "Paris"
        region_id: 11
        department_code: 75
        prefix: ""
```

Which is far more coherent. For information, region `11` is `Île-de-France` according to [INSEE file](http://www.insee.fr/fr/methodes/nomenclatures/cog/telechargement/2014/txt/reg2014.txt).
